(define (make-monitored procedure)
  (let ((count 0))
    (lambda (arg)
      (cond ((eq? arg 'how-many-calls) count)
	    ((eq? arg 'reset-count) (set! count 0))
	    (else (begin (set! count (+ count 1))
			 (procedure arg)))))))
