(define (make-account balance pwd)
  (define (call-the-cops) "call the cops")
  (let ((limit 7) (count 0))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch p m)
      (if (not (eq? p pwd))
	  (lambda (x)
	    (if (> count limit)
		(call-the-cops)
		(begin (set! count (+ count 1)) "Incorrect password")))
	  (begin (set! count 0)
		 (cond ((eq? m 'withdraw) withdraw)
		       ((eq? m 'deposit) deposit)
		       (else (error "Unknow request -- MAKE-ACCOUNT"
				    m))))))
    dispatch))
